-- MySQL Script generated by MySQL Workbench
-- 03/13/15 10:32:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CARISMA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CARISMA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CARISMA` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `CARISMA` ;

-- -----------------------------------------------------
-- Table `CARISMA`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`timestamps` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `CARISMA`.`provinsi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`provinsi` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`provinsi` (
  `id_provinsi` VARCHAR(10) NOT NULL,
  `nama_provinsi` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_provinsi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`kota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`kota` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`kota` (
  `id_kota` VARCHAR(10) NOT NULL,
  `provinsi_id_provinsi` VARCHAR(10) NOT NULL,
  `nama_kota` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_kota`, `provinsi_id_provinsi`),
  INDEX `fk_kota_provinsi1_idx` (`provinsi_id_provinsi` ASC),
  CONSTRAINT `fk_kota_provinsi1`
    FOREIGN KEY (`provinsi_id_provinsi`)
    REFERENCES `CARISMA`.`provinsi` (`id_provinsi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`user` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `registered` DATETIME NOT NULL,
  `lastlogin` DATETIME NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`pasien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`pasien` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`pasien` (
  `id_pasien` VARCHAR(10) NOT NULL,
  `kota_id_kota` VARCHAR(10) NOT NULL,
  `user_id_user` INT NOT NULL,
  `nama_pasien` VARCHAR(45) NOT NULL,
  `alamat_pasien` VARCHAR(45) NOT NULL,
  `kartuid_pasien` VARCHAR(45) NOT NULL,
  `nokartuid_pasien` VARCHAR(45) NOT NULL,
  `telp_pasien` VARCHAR(45) NULL,
  `hp_pasien` VARCHAR(45) NULL,
  `tempatlahir_pasien` VARCHAR(45) NOT NULL,
  `tgllahir_pasien` DATE NOT NULL,
  `kelamin_pasien` VARCHAR(1) NOT NULL,
  `darah_pasien` VARCHAR(2) NOT NULL DEFAULT '-',
  `regdate_pasien` DATE NOT NULL,
  PRIMARY KEY (`id_pasien`),
  INDEX `fk_pasien_kota1_idx` (`kota_id_kota` ASC),
  INDEX `fk_pasien_user1_idx` (`user_id_user` ASC),
  UNIQUE INDEX `user_id_user_UNIQUE` (`user_id_user` ASC),
  CONSTRAINT `fk_pasien_kota1`
    FOREIGN KEY (`kota_id_kota`)
    REFERENCES `CARISMA`.`kota` (`id_kota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pasien_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `CARISMA`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`kartupasien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`kartupasien` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`kartupasien` (
  `pasien_id_pasien` VARCHAR(10) NOT NULL,
  `cetak_kartupasien` DATE NOT NULL,
  `berlakusampai_kartupasien` DATE NOT NULL,
  PRIMARY KEY (`pasien_id_pasien`),
  CONSTRAINT `fk_kartupasien_pasien1`
    FOREIGN KEY (`pasien_id_pasien`)
    REFERENCES `CARISMA`.`pasien` (`id_pasien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`poli`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`poli` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`poli` (
  `id_poli` VARCHAR(5) NOT NULL,
  `nama_poli` VARCHAR(45) NOT NULL,
  `keterangan` VARCHAR(45) NULL,
  PRIMARY KEY (`id_poli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`dokter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`dokter` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`dokter` (
  `id_dokter` VARCHAR(10) NOT NULL,
  `poli_id_poli` VARCHAR(5) NOT NULL,
  `user_id_user` INT NOT NULL,
  `nama_dokter` VARCHAR(45) NOT NULL,
  `alamat_dokter` VARCHAR(45) NOT NULL,
  `nokartuid_dokter` VARCHAR(45) NOT NULL,
  `telp_dokter` VARCHAR(45) NULL,
  `hp1_dokter` VARCHAR(45) NULL,
  `hp2_dokter` VARCHAR(45) NULL,
  `tempatlahir_dokter` VARCHAR(45) NOT NULL,
  `tgllahir_dokter` DATE NOT NULL,
  `kelamin_dokter` VARCHAR(1) NOT NULL,
  `darah_dokter` VARCHAR(2) NOT NULL DEFAULT '-',
  `bank_dokter` VARCHAR(45) NULL,
  `norek_dokter` VARCHAR(45) NULL,
  `foto_dokter` BLOB NULL,
  `gajifix_dokter` INT NULL,
  `gajilembur_dokter` INT NULL,
  `gajikonsul_dokter` DOUBLE NULL,
  PRIMARY KEY (`id_dokter`),
  INDEX `fk_dokter_poli1_idx` (`poli_id_poli` ASC),
  INDEX `fk_dokter_user1_idx` (`user_id_user` ASC),
  UNIQUE INDEX `user_id_user_UNIQUE` (`user_id_user` ASC),
  CONSTRAINT `fk_dokter_poli1`
    FOREIGN KEY (`poli_id_poli`)
    REFERENCES `CARISMA`.`poli` (`id_poli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dokter_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `CARISMA`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`resep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`resep` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`resep` (
  `id_resep` VARCHAR(45) NOT NULL,
  `keterangan` VARCHAR(45) NULL,
  PRIMARY KEY (`id_resep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`rekammedik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`rekammedik` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`rekammedik` (
  `id_rekammedik` VARCHAR(45) NOT NULL,
  `dokter_id_dokter` VARCHAR(10) NOT NULL,
  `pasien_id_pasien` VARCHAR(10) NOT NULL,
  `tgl_rekammedik` DATETIME NOT NULL,
  `keluhan_rekammedik` VARCHAR(512) NULL,
  `pemeriksaan_rekammedik` VARCHAR(512) NULL,
  `terapi_rekammedik` VARCHAR(512) NULL,
  `alergiobat_rekammedik` VARCHAR(50) NULL,
  `kesimpulan_rekammedis` VARCHAR(50) NULL,
  `kondisipasienkeluar_rekammedis` VARCHAR(60) NOT NULL,
  `resep_id_resep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rekammedik`),
  INDEX `fk_rekammedis_dokter1_idx` (`dokter_id_dokter` ASC),
  INDEX `fk_rekammedis_pasien1_idx` (`pasien_id_pasien` ASC),
  INDEX `fk_rekammedis_resep1_idx` (`resep_id_resep` ASC),
  CONSTRAINT `fk_rekammedis_dokter1`
    FOREIGN KEY (`dokter_id_dokter`)
    REFERENCES `CARISMA`.`dokter` (`id_dokter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rekammedis_pasien1`
    FOREIGN KEY (`pasien_id_pasien`)
    REFERENCES `CARISMA`.`pasien` (`id_pasien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rekammedis_resep1`
    FOREIGN KEY (`resep_id_resep`)
    REFERENCES `CARISMA`.`resep` (`id_resep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`penyakit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`penyakit` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`penyakit` (
  `id_penyakit` VARCHAR(10) NOT NULL,
  `nama_penyakit` VARCHAR(45) NOT NULL,
  `deskripsi_penyakit` VARCHAR(512) NULL,
  PRIMARY KEY (`id_penyakit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`jadwaldokter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`jadwaldokter` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`jadwaldokter` (
  `dokter_id_dokter` VARCHAR(10) NOT NULL,
  `hari_jadwaldokter` VARCHAR(45) NOT NULL,
  `shift_jadwaldokter` VARCHAR(45) NOT NULL,
  `keterangan` VARCHAR(45) NULL,
  PRIMARY KEY (`dokter_id_dokter`),
  CONSTRAINT `fk_jadwaldokter_dokter1`
    FOREIGN KEY (`dokter_id_dokter`)
    REFERENCES `CARISMA`.`dokter` (`id_dokter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`rekammedis_penyakit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`rekammedis_penyakit` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`rekammedis_penyakit` (
  `rekammedik_id_rekammedik` VARCHAR(45) NOT NULL,
  `penyakit_id_penyakit` VARCHAR(10) NOT NULL,
  INDEX `fk_rekammedis_penyakit_rekammedis1_idx` (`rekammedik_id_rekammedik` ASC),
  INDEX `fk_rekammedis_penyakit_penyakit1_idx` (`penyakit_id_penyakit` ASC),
  CONSTRAINT `fk_rekammedis_penyakit_rekammedis1`
    FOREIGN KEY (`rekammedik_id_rekammedik`)
    REFERENCES `CARISMA`.`rekammedik` (`id_rekammedik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rekammedis_penyakit_penyakit1`
    FOREIGN KEY (`penyakit_id_penyakit`)
    REFERENCES `CARISMA`.`penyakit` (`id_penyakit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`transaksijualobat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`transaksijualobat` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`transaksijualobat` (
  `id_transaksijual` VARCHAR(45) NOT NULL,
  `date_transaksijual` DATE NULL,
  `keterangan` VARCHAR(45) NULL,
  PRIMARY KEY (`id_transaksijual`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`kamar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`kamar` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`kamar` (
  `id_kamar` INT NOT NULL,
  `nama_kamar` VARCHAR(45) NOT NULL,
  `kelas` VARCHAR(45) NOT NULL,
  `tarif` INT NOT NULL,
  PRIMARY KEY (`id_kamar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`pasien_kamar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`pasien_kamar` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`pasien_kamar` (
  `id_peminjaman` VARCHAR(10) NOT NULL,
  `kamar_id_kamar` INT NOT NULL,
  `datein_pasien_kamar` DATETIME NOT NULL,
  `dateout_pasien_kamar` DATETIME NOT NULL,
  `keterangan` VARCHAR(45) NULL,
  PRIMARY KEY (`id_peminjaman`),
  CONSTRAINT `fk_pasien_kamar_kamar1`
    FOREIGN KEY (`kamar_id_kamar`)
    REFERENCES `CARISMA`.`kamar` (`id_kamar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`kunjungan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`kunjungan` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`kunjungan` (
  `id_kunjungan` VARCHAR(45) NOT NULL,
  `pasien_id_pasien` VARCHAR(10) NOT NULL,
  `rekammedik_id_rekammedik` VARCHAR(45) NOT NULL,
  `transaksijualobat_id_transaksijual` VARCHAR(45) NULL DEFAULT 'Kosong',
  `pasien_kamar_id_peminjaman` VARCHAR(10) NULL DEFAULT 'Kosong',
  `tanggaljam_kunjungan` DATETIME NOT NULL,
  `biaya_kunjungan` INT NULL,
  PRIMARY KEY (`id_kunjungan`),
  INDEX `fk_kunjungan_pasien1_idx` (`pasien_id_pasien` ASC),
  INDEX `fk_kunjungan_rekammedis1_idx` (`rekammedik_id_rekammedik` ASC),
  INDEX `fk_kunjungan_transaksijualobat1_idx` (`transaksijualobat_id_transaksijual` ASC),
  INDEX `fk_kunjungan_pasien_kamar1_idx` (`pasien_kamar_id_peminjaman` ASC),
  CONSTRAINT `fk_kunjungan_pasien1`
    FOREIGN KEY (`pasien_id_pasien`)
    REFERENCES `CARISMA`.`pasien` (`id_pasien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kunjungan_rekammedis1`
    FOREIGN KEY (`rekammedik_id_rekammedik`)
    REFERENCES `CARISMA`.`rekammedik` (`id_rekammedik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kunjungan_transaksijualobat1`
    FOREIGN KEY (`transaksijualobat_id_transaksijual`)
    REFERENCES `CARISMA`.`transaksijualobat` (`id_transaksijual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kunjungan_pasien_kamar1`
    FOREIGN KEY (`pasien_kamar_id_peminjaman`)
    REFERENCES `CARISMA`.`pasien_kamar` (`id_peminjaman`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`antrian`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`antrian` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`antrian` (
  `id_antrian` VARCHAR(45) NOT NULL,
  `pasien_id_pasien` VARCHAR(10) NOT NULL,
  `dokter_id_dokter` VARCHAR(10) NOT NULL,
  `nomor_antrian` INT NOT NULL,
  `jenis_antrian` VARCHAR(45) NOT NULL,
  `tgl_antrian` DATE NOT NULL,
  `hadir` VARCHAR(1) NULL,
  PRIMARY KEY (`id_antrian`),
  INDEX `fk_antrian_pasien1_idx` (`pasien_id_pasien` ASC),
  INDEX `fk_antrian_dokter1_idx` (`dokter_id_dokter` ASC),
  CONSTRAINT `fk_antrian_pasien1`
    FOREIGN KEY (`pasien_id_pasien`)
    REFERENCES `CARISMA`.`pasien` (`id_pasien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_antrian_dokter1`
    FOREIGN KEY (`dokter_id_dokter`)
    REFERENCES `CARISMA`.`dokter` (`id_dokter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`pegawai`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`pegawai` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`pegawai` (
  `id_pegawai` VARCHAR(45) NOT NULL,
  `user_id_user` INT NOT NULL,
  `nama_pegawai` VARCHAR(45) NOT NULL,
  `alamat_pegawai` VARCHAR(45) NOT NULL,
  `nokartuid_pegawai` VARCHAR(45) NOT NULL,
  `telp_pegawai` VARCHAR(45) NULL,
  `hp1_pegawai` VARCHAR(45) NULL,
  `hp2_pegawai` VARCHAR(45) NULL,
  `tempatlahir_pegawai` VARCHAR(45) NOT NULL,
  `tgllahir_pegawai` VARCHAR(45) NOT NULL,
  `kelamin_pegawai` VARCHAR(1) NOT NULL,
  `darah_pegawai` VARCHAR(2) NOT NULL DEFAULT '-',
  `jabatan_pegawai` VARCHAR(45) NOT NULL,
  `bank_pegawai` VARCHAR(45) NULL,
  `norek_pegawai` VARCHAR(45) NULL,
  `foto_pegawai` BLOB NULL,
  `gajifix_pegawai` INT NULL,
  `gajilembur_pegawai` INT NULL,
  PRIMARY KEY (`id_pegawai`),
  INDEX `fk_pegawai_user1_idx` (`user_id_user` ASC),
  UNIQUE INDEX `user_id_user_UNIQUE` (`user_id_user` ASC),
  CONSTRAINT `fk_pegawai_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `CARISMA`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`jadwalpegawai`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`jadwalpegawai` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`jadwalpegawai` (
  `pegawai_id_pegawai` VARCHAR(45) NOT NULL,
  `hari_jadwalpegawai` VARCHAR(45) NOT NULL,
  `shift_jadwalpegawai` VARCHAR(45) NOT NULL,
  `keterangan` VARCHAR(45) NULL,
  PRIMARY KEY (`pegawai_id_pegawai`),
  CONSTRAINT `fk_jadwalpegawai_pegawai1`
    FOREIGN KEY (`pegawai_id_pegawai`)
    REFERENCES `CARISMA`.`pegawai` (`id_pegawai`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`absensidokter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`absensidokter` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`absensidokter` (
  `dokter_id_dokter` VARCHAR(10) NOT NULL,
  `kehadiranreguler_dokter` VARCHAR(1) NOT NULL DEFAULT 0,
  `kehadiranlembur_dokter` VARCHAR(1) NOT NULL DEFAULT 0,
  `date_absensidokter` DATE NOT NULL,
  INDEX `fk_absensidokter_dokter1_idx` (`dokter_id_dokter` ASC),
  CONSTRAINT `fk_absensidokter_dokter1`
    FOREIGN KEY (`dokter_id_dokter`)
    REFERENCES `CARISMA`.`dokter` (`id_dokter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`absensipegawai`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`absensipegawai` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`absensipegawai` (
  `pegawai_id_pegawai` VARCHAR(45) NOT NULL,
  `kehadiranreguler_pegawai` VARCHAR(1) NOT NULL DEFAULT 0,
  `kehadiranlembur_pegawai` VARCHAR(1) NOT NULL DEFAULT 0,
  `date_absensipegawai` DATE NOT NULL,
  INDEX `fk_absensipegawai_pegawai1_idx` (`pegawai_id_pegawai` ASC),
  CONSTRAINT `fk_absensipegawai_pegawai1`
    FOREIGN KEY (`pegawai_id_pegawai`)
    REFERENCES `CARISMA`.`pegawai` (`id_pegawai`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`gajidokter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`gajidokter` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`gajidokter` (
  `dokter_id_dokter` VARCHAR(10) NOT NULL,
  `bulanan_gajidokter` INT NOT NULL,
  `dibayarkan_gajidokter` DATE NOT NULL,
  `bonus_gajidokter` INT NULL,
  `keterangan_gajidokter` VARCHAR(45) NULL,
  INDEX `fk_gajidokter_dokter1_idx` (`dokter_id_dokter` ASC),
  CONSTRAINT `fk_gajidokter_dokter1`
    FOREIGN KEY (`dokter_id_dokter`)
    REFERENCES `CARISMA`.`dokter` (`id_dokter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`gajipegawai`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`gajipegawai` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`gajipegawai` (
  `pegawai_id_pegawai` VARCHAR(45) NOT NULL,
  `bulanan_gajipegawai` INT NULL,
  `dibayarkan_gajipegawai` DATE NULL,
  `bonus_gajipegawai` INT NULL,
  `keterangan_gajipegawai` VARCHAR(45) NULL,
  INDEX `fk_gajipegawai_pegawai1_idx` (`pegawai_id_pegawai` ASC),
  CONSTRAINT `fk_gajipegawai_pegawai1`
    FOREIGN KEY (`pegawai_id_pegawai`)
    REFERENCES `CARISMA`.`pegawai` (`id_pegawai`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`obat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`obat` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`obat` (
  `id_obat` INT NOT NULL,
  `nama_obat` VARCHAR(45) NULL,
  `qty_obat` INT NULL,
  `jenis_obat` VARCHAR(45) NULL,
  `keterangan` VARCHAR(45) NULL,
  `hargajual_obat` INT NULL,
  PRIMARY KEY (`id_obat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`detailobat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`detailobat` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`detailobat` (
  `id_detail` INT NOT NULL,
  `obat_id_obat` INT NOT NULL,
  `tglkadaluarsa_detail` DATE NULL,
  PRIMARY KEY (`id_detail`),
  INDEX `fk_detailobat_obat1_idx` (`obat_id_obat` ASC),
  CONSTRAINT `fk_detailobat_obat1`
    FOREIGN KEY (`obat_id_obat`)
    REFERENCES `CARISMA`.`obat` (`id_obat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`rakobat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`rakobat` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`rakobat` (
  `id_rak` INT NOT NULL,
  `obat_id_obat` INT NOT NULL,
  `nama_rak` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rak`),
  INDEX `fk_rakobat_obat1_idx` (`obat_id_obat` ASC),
  CONSTRAINT `fk_rakobat_obat1`
    FOREIGN KEY (`obat_id_obat`)
    REFERENCES `CARISMA`.`obat` (`id_obat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`detailtransaksijualobat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`detailtransaksijualobat` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`detailtransaksijualobat` (
  `transaksijualobat_id_transaksijual` VARCHAR(45) NOT NULL,
  `obat_id_obat` INT NOT NULL,
  `qty` INT NOT NULL,
  PRIMARY KEY (`transaksijualobat_id_transaksijual`, `obat_id_obat`),
  INDEX `fk_detailtransaksijualobat_obat1_idx` (`obat_id_obat` ASC),
  INDEX `fk_detailtransaksijualobat_transaksijualobat1_idx` (`transaksijualobat_id_transaksijual` ASC),
  CONSTRAINT `fk_detailtransaksijualobat_obat1`
    FOREIGN KEY (`obat_id_obat`)
    REFERENCES `CARISMA`.`obat` (`id_obat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detailtransaksijualobat_transaksijualobat1`
    FOREIGN KEY (`transaksijualobat_id_transaksijual`)
    REFERENCES `CARISMA`.`transaksijualobat` (`id_transaksijual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`transaksibeliobat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`transaksibeliobat` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`transaksibeliobat` (
  `id_transaksibeliobat` VARCHAR(45) NOT NULL,
  `date_transaksibeli` DATE NULL,
  `keterangan` VARCHAR(45) NULL,
  `hargabeli_obat` INT NULL,
  PRIMARY KEY (`id_transaksibeliobat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`detailtransaksibeliobat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`detailtransaksibeliobat` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`detailtransaksibeliobat` (
  `transaksibeliobat_id_transaksibeliobat` VARCHAR(45) NOT NULL,
  `obat_id_obat` INT NOT NULL,
  `qty` INT NOT NULL,
  PRIMARY KEY (`transaksibeliobat_id_transaksibeliobat`, `obat_id_obat`),
  INDEX `fk_detailtransaksibeliobat_obat1_idx` (`obat_id_obat` ASC),
  CONSTRAINT `fk_detailtransaksibeliobat_transaksibeliobat1`
    FOREIGN KEY (`transaksibeliobat_id_transaksibeliobat`)
    REFERENCES `CARISMA`.`transaksibeliobat` (`id_transaksibeliobat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detailtransaksibeliobat_obat1`
    FOREIGN KEY (`obat_id_obat`)
    REFERENCES `CARISMA`.`obat` (`id_obat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CARISMA`.`detailresep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARISMA`.`detailresep` ;

CREATE TABLE IF NOT EXISTS `CARISMA`.`detailresep` (
  `resep_id_resep` VARCHAR(45) NOT NULL,
  `namaobat_resep` VARCHAR(45) NULL,
  `qty_resep` INT NULL,
  `aturanpakai_resep` VARCHAR(45) NULL,
  INDEX `fk_detailresep_resep1_idx` (`resep_id_resep` ASC),
  CONSTRAINT `fk_detailresep_resep1`
    FOREIGN KEY (`resep_id_resep`)
    REFERENCES `CARISMA`.`resep` (`id_resep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `CARISMA`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `CARISMA`;
INSERT INTO `CARISMA`.`user` (`id_user`, `username`, `password`, `registered`, `lastlogin`, `role`) VALUES (1, 'carisma', 'carisma', '2015-03-13 00:00:00', '2015-03-13 00:00:00', 'administrator');

COMMIT;

